Repository wecode-bootcamp-korea/49-3rd-WEE.T-backend, pull requests merged in 2023-10, with the labels that each got.

#1 초기세팅 완료
   .env sample
  .env.test
  .gitignore
  app.js
  db/migrations/20231011110011_create_socials_table.sql
  db/migrations/20231011110012_create_gender_table.sql
  db/migrations/20231011110013_create_subscribes_table.sql
  db/migrations/20231011110014_create_badges_table.sql
  db/migrations/20231011110015_create_users_table.sql
  db/migrations/20231011110016_create_nutrition_table.sql
  db/migrations/20231011110017_create_foods_table.sql
  db/migrations/20231011110018_create_parts_table.sql
  db/migrations/20231011110019_create_exercises_table.sql
  db/migrations/20231011110630_create_health_infos_table.sql
  db/migrations/20231011112758_create_feeds_table.sql
  db/migrations/20231011113232_create_feed_images_table.sql
  db/migrations/20231011113913_create_comments_table.sql
  db/migrations/20231011114119_create_payments_table.sql
  db/migrations/20231011114211_create_subscription_table.sql
  db/migrations/20231011114212_create_orders_table.sql
  package-lock.json
  package.json
  server.js
  src/controllers/index.js
  src/models/dataSource.js
  src/models/index.js
  src/routes/index.js
  src/services/index.js
Labels: 멘토 리뷰 요청

#4 dbmate 수정 파일 추가
  db/migrations/20231015075116_modify_socials_table.sql
  db/migrations/20231015075423_modify_gender_table.sql
  db/migrations/20231015080633_modify_subscribes_table.sql
  db/migrations/20231015080843_modify_badges_table.sql
  db/migrations/20231015081207_modify_users_table.sql
  db/migrations/20231015083136_modify_nutrition_table.sql
  db/migrations/20231015083604_modify_foods_table.sql
  db/migrations/20231015085027_modify_parts_table.sql
  db/migrations/20231015090202_modify_exercises_table.sql
  db/migrations/20231015091021_modify_health_infos_table.sql
  db/migrations/20231015093124_modify_feeds_table.sql
  db/migrations/20231015102223_modify_feed_images_table.sql
  db/migrations/20231015102453_modify_comments_table.sql
  db/migrations/20231015102726_modify_payments_table.sql
  db/migrations/20231015102856_modify_subscription_table.sql
  db/migrations/20231015103239_modify_orders_table.sql
Labels: 멘토 리뷰 요청

#5 dbmate 마이그레이션 파일 수정
  db/migrations/20231015075116_modify_socials_table.sql
  db/migrations/20231015075423_modify_gender_table.sql
  db/migrations/20231015080633_modify_subscribes_table.sql
  db/migrations/20231015080843_modify_badges_table.sql
  db/migrations/20231015081207_modify_users_table.sql
  db/migrations/20231015083136_modify_nutrition_table.sql
  db/migrations/20231015083604_modify_foods_table.sql
  db/migrations/20231015085027_modify_parts_table.sql
  db/migrations/20231015090202_modify_exercises_table.sql
  db/migrations/20231015091021_modify_health_infos_table.sql
  db/migrations/20231015093124_modify_feeds_table.sql
  db/migrations/20231015102223_modify_feed_images_table.sql
  db/migrations/20231015102453_modify_comments_table.sql
  db/migrations/20231015102726_modify_payments_table.sql
  db/migrations/20231015102856_modify_subscription_table.sql
  db/migrations/20231015103239_modify_orders_table.sql
Labels: 멘토 리뷰 요청

#10 회원정보 조회 API 구현
  src/controllers/userController.js
  src/models/userDao.js
  src/routes/userRouter.js
  src/services/userService.js
  tests/user.test.js
Labels: 수정 요청

#11 서비스 정보 조회 API 구현
  src/controllers/index.js
  src/controllers/statisticsController.js
  src/models/index.js
  src/models/statisticsDao.js
  src/routes/index.js
  src/routes/statisticsRouter.js
  src/services/index.js
  src/services/statisticsService.js
  tests/statistics.test.js
  tests/user.test.js
Labels: 멘토 리뷰 요청

#9 Feature/feed
  .env.test
  app.js
  db/migrations/20231016175641_modify_feed_images_table_2.sql
  db/migrations/20231610181129_modify_feed_images_table_3.sql
  package-lock.json
  package.json
  src/config/s3.js
  src/controllers/feedController.js
  src/controllers/index.js
  src/models/feedDao.js
  src/models/feedQueryBuilder.js
  src/models/index.js
  src/models/trainingDao.js
  src/routes/authRouter.js
  src/routes/feedRouter.js
  src/routes/index.js
  src/services/feedService.js
  src/services/index.js
  tests/feed.test.js
Labels: 멘토 리뷰 요청, 수정 요청

#12 구독권 조회 API
  db/migrations/20231011114211_create_subscription_table.sql
  src/controllers/index.js
  src/controllers/subscribeController.js
  src/models/index.js
  src/models/subscribeDao.js
  src/routes/index.js
  src/routes/subscribeRouter.js
  src/services/index.js
  src/services/subscribeService.js
  tests/subscribe.test.js
Labels: 수정 요청

#20 결제내역 조회 API
  src/controllers/userController.js
  src/models/index.js
  src/models/orderListDao.js
  src/routes/userRouter.js
  src/services/userService.js
  tests/order.test.js
Labels: 멘토 리뷰 요청

#22 결제요청 API
  src/controllers/subscribeController.js
  src/models/subscribeDao.js
  src/routes/subscribeRouter.js
  src/services/subscribeService.js
Labels: 멘토 리뷰 요청

#13 Feature/comment
  db/migrations/20231011112758_create_feeds_table.sql
  db/migrations/20231011113913_create_comments_table.sql
  src/controllers/commentController.js
  src/controllers/index.js
  src/models/commentDao.js
  src/models/index.js
  src/routes/authRouter.js
  src/routes/commentRouter.js
  src/routes/index.js
  src/services/commentService.js
  src/services/index.js
  tests/comment.test.js
Labels: 멘토 리뷰 요청
